events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;
        client_max_body_size 1g;

        root /usr/share/nginx/html;
        index index.html;

        location /static/ {
            alias /app/backend/staticfiles/;
            access_log off;
            expires 7d;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 900s;
            proxy_send_timeout 900s;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
