# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0006_testcase_project_isolation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='assertion_result',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='response_body',
            field=models.TextField(blank=True, null=True, verbose_name='???'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='response_time_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='success',
            field=models.IntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariorunhistory',
            name='context_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariorunhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariorunhistory',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='scenariorunhistory',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariorunhistory',
            name='results',
            field=models.JSONField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='scenariorunhistory',
            name='success',
            field=models.IntegerField(default=0, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='assertions',
            field=models.JSONField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='continue_on_fail',
            field=models.BooleanField(default=False, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='extract_rules',
            field=models.JSONField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='overrides',
            field=models.JSONField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='preconditions',
            field=models.JSONField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='step_name',
            field=models.CharField(max_length=128, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='step_order',
            field=models.IntegerField(default=1, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assert_contains',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='??????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='assert_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='base_url',
            field=models.CharField(max_length=255, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='body_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON???'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='body_text',
            field=models.TextField(blank=True, null=True, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='headers',
            field=models.JSONField(blank=True, null=True, verbose_name='???'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='method',
            field=models.CharField(default='GET', max_length=16, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=128, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='path',
            field=models.CharField(max_length=255, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='timeout_seconds',
            field=models.IntegerField(default=10, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='stop_on_failure',
            field=models.BooleanField(default=True, verbose_name='?????'),
        ),
        migrations.AlterField(
            model_name='testscenario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='????'),
        ),
    ]
