# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0007_alter_project_created_at_alter_project_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="custom_assertions",
            field=models.JSONField(blank=True, null=True, verbose_name="??????"),
        ),
    ]
