# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0008_testcase_custom_assertions"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="verify_ssl",
            field=models.BooleanField(default=True, verbose_name="SSL????"),
        ),
    ]
