# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0009_testcase_verify_ssl"),
    ]

    operations = [
        migrations.AddField(
            model_name="runhistory",
            name="request_snapshot",
            field=models.JSONField(blank=True, null=True, verbose_name="??????"),
        ),
        migrations.AddField(
            model_name="runhistory",
            name="response_content_type",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="??????"),
        ),
        migrations.AddField(
            model_name="runhistory",
            name="response_headers",
            field=models.JSONField(blank=True, null=True, verbose_name="??????"),
        ),
    ]
