# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0010_runhistory_request_response_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEnvironment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="????")),
                ("description", models.CharField(blank=True, max_length=255, null=True, verbose_name="????")),
                ("base_url", models.CharField(max_length=255, verbose_name="????")),
                ("variables", models.JSONField(blank=True, null=True, verbose_name="????")),
                ("is_active", models.BooleanField(default=True, verbose_name="????")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="????")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="????")),
                (
                    "project",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="autotest.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_environments",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectenvironment",
            constraint=models.UniqueConstraint(fields=("project", "name"), name="uniq_env_name_in_project"),
        ),
        migrations.AddField(
            model_name="testcase",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_cases",
                to="autotest.projectenvironment",
            ),
        ),
    ]
