# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0011_environment_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='????')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='????')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='????')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='????')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_modules', to='autotest.project')),
            ],
            options={
                'db_table': 'api_modules',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='autotest.apimodule'),
        ),
        migrations.AddConstraint(
            model_name='apimodule',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_api_module_name_in_project'),
        ),
    ]
