# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0012_apimodule_testcase_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='post_processors',
            field=models.JSONField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='pre_processors',
            field=models.JSONField(blank=True, null=True, verbose_name='??????'),
        ),
    ]
