# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0013_testcase_post_processors_testcase_pre_processors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='post_processors',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='pre_processors',
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='post_processors',
            field=models.JSONField(blank=True, null=True, verbose_name='??????'),
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='pre_processors',
            field=models.JSONField(blank=True, null=True, verbose_name='??????'),
        ),
    ]
