# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0014_remove_testcase_post_processors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testscenario",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_scenarios",
                to="autotest.apimodule",
            ),
        ),
    ]
