# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0015_testscenario_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalVariable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="变量名")),
                ("value", models.JSONField(blank=True, null=True, verbose_name="变量值")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_variables",
                        to="autotest.project",
                    ),
                ),
            ],
            options={
                "db_table": "global_variables",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="globalvariable",
            constraint=models.UniqueConstraint(fields=("project", "name"), name="uniq_global_var_name_in_project"),
        ),
    ]
