# 作者: lxl
# 说明: 为 ApiModule 增加 parent 树形字段。
# Generated by Django 4.1.13 on 2026-02-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0016_globalvariable"),
    ]

    operations = [
        migrations.AddField(
            model_name="apimodule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="autotest.apimodule",
            ),
        ),
    ]
