# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0018_testscenario_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='timeout_seconds',
            field=models.IntegerField(default=1, verbose_name='????'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='verify_ssl',
            field=models.BooleanField(default=False, verbose_name='SSL????'),
        ),
    ]
