# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0019_alter_testcase_timeout_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectenvironment",
            name="default_headers",
            field=models.JSONField(blank=True, null=True, verbose_name="默认 Header"),
        ),
    ]
