# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-03-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0020_projectenvironment_default_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Data Set Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Set Description')),
                ('source_type', models.CharField(default='table', max_length=16, verbose_name='Source Type')),
                ('data_rows', models.JSONField(blank=True, null=True, verbose_name='Table Rows')),
                ('raw_text', models.TextField(blank=True, null=True, verbose_name='Raw Text')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_data_sets', to='autotest.apimodule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_data_sets', to='autotest.project')),
            ],
            options={
                'db_table': 'scenario_data_sets',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='testscenario',
            name='param_enabled',
            field=models.BooleanField(default=False, verbose_name='Param Enabled'),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='data_mode',
            field=models.CharField(default='all', max_length=16, verbose_name='Data Run Mode'),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='data_pick',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Pick Config'),
        ),
        migrations.AddField(
            model_name='testscenario',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_scenarios', to='autotest.scenariodataset'),
        ),
        migrations.AddField(
            model_name='scenariorunhistory',
            name='iterations',
            field=models.JSONField(blank=True, null=True, verbose_name='Iteration Results'),
        ),
        migrations.AddConstraint(
            model_name='scenariodataset',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_dataset_name_in_project'),
        ),
    ]
