# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0021_scenariorunhistory_iterations_testscenario_data_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenario',
            name='param_retry_count',
            field=models.IntegerField(default=0, verbose_name='Param Retry Count'),
        ),
    ]
