# 作者: lxl
# 说明: 业务模块实现。
# Generated by Django 4.1.13 on 2026-03-04 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("autotest", "0025_loginauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(blank=True, max_length=150, null=True, verbose_name="Username")),
                ("method", models.CharField(max_length=8, verbose_name="Method")),
                ("path", models.CharField(max_length=255, verbose_name="Path")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="Status Code")),
                ("success", models.IntegerField(default=0, verbose_name="Success")),
                ("detail", models.CharField(blank=True, max_length=255, null=True, verbose_name="Detail")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "operation_audit_logs",
                "ordering": ["-id"],
            },
        ),
    ]
