# 作者: lxl
# 说明: 后端路由入口。
from django.urls import path

from autotest import views

urlpatterns = [
    path("health", views.health),
    path("auth/login", views.auth_login),
    path("auth/me", views.auth_me),
    path("auth/logout", views.auth_logout),
    path("auth/change-password", views.auth_change_password),
    path("auth/users", views.auth_user_list_create),
    path("auth/users/<int:user_id>", views.auth_user_detail),
    path("projects", views.project_list_create),
    path("projects/<int:project_id>", views.project_detail),
    path("data-sets", views.data_set_list_create),
    path("data-sets/<int:data_set_id>", views.data_set_detail),
    path("modules", views.module_list_create),
    path("modules/<int:module_id>", views.module_detail),
    path("modules/<int:module_id>/run-scenarios", views.run_module_scenarios),
    path("test-cases", views.test_case_list_create),
    path("test-cases/preview", views.preview_test_case_runtime),
    path("test-cases/<int:case_id>", views.test_case_detail),
    path("test-cases/<int:case_id>/run", views.run_test_case),
    path("run-histories", views.run_history_list),
    path("scenarios", views.scenario_list_create),
    path("scenarios/preview", views.preview_scenario_runtime),
    path("scenarios/preview-batch", views.preview_scenarios_batch),
    path("scenarios/debug-step", views.debug_scenario_step_runtime),
    path("scenarios/reorder", views.scenario_reorder),
    path("scenarios/run-batch", views.run_scenarios_batch),
    path("scenarios/<int:scenario_id>", views.scenario_detail),
    path("scenarios/<int:scenario_id>/run", views.run_scenario),
    path("scenario-run-histories", views.scenario_run_history_list),
    path("scenario-run-histories/batch-delete", views.scenario_run_history_batch_delete),
    path("scenario-run-histories/<int:history_id>", views.scenario_run_history_detail),
    path("dashboard/summary", views.dashboard_summary),
    path("test-suites", views.suite_list),
    path("environments", views.environment_list),
    path("environments/<int:env_id>", views.environment_detail),
    path("monitor/platforms", views.monitor_platform_list_create),
    path("monitor/platforms/<int:platform_id>", views.monitor_platform_detail),
    path("monitor/platforms/<int:platform_id>/deploy", views.monitor_platform_deploy),
    path("monitor/platforms/<int:platform_id>/upload-package", views.monitor_platform_upload_package),
    path("monitor/platforms/<int:platform_id>/status", views.monitor_platform_status),
    path("monitor/platforms/<int:platform_id>/logs", views.monitor_platform_logs),
    path("monitor/platforms/<int:platform_id>/targets", views.monitor_platform_targets),
    path("monitor/platforms/<int:platform_id>/metrics/latest", views.monitor_platform_metrics_latest),
    path("monitor/platforms/<int:platform_id>/metrics/history", views.monitor_platform_metrics_history),
    path("rbac/overview", views.rbac_overview),
    path("ai/generate-test-cases", views.ai_generate_test_cases),
    path("ai/generate-from-openapi", views.ai_generate_from_openapi),
    path("ai/validate-config", views.ai_validate_config),
]
